- hosts: all
  sudo: true
  tasks:
    - name: Update package information [deb]
      apt: update_cache=yes
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - name: Upgrade packages [deb]
      apt: upgrade=full
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Upgrade packages [rpm]
      dnf: name=* state=latest
      when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Fedora"

